CREATE TABLE
    gitbook
    (
        SEQ bigint(6) unsigned NOT NULL AUTO_INCREMENT,
        book_name VARCHAR(2048),
        book_path VARCHAR(500),
        book_info VARCHAR(500),
        SORT_INFO CHAR(2),
        create_date VARCHAR(18),
        PRIMARY KEY (SEQ)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (1, 'Apache2.2中文官方文档', 'https://www.gitbook.com/download/pdf/book/wizardforcel/apache-doc', 'https://www.gitbook.com/book/wizardforcel/apache-doc', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (2, 'network-detail', 'https://www.gitbook.com/download/pdf/book/unanao/network-detail', 'https://www.gitbook.com/book/unanao/network-detail', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (3, 'AFNetworking框架的使用', 'https://www.gitbook.com/download/pdf/book/zfzlj/afnetworking-', 'https://www.gitbook.com/book/zfzlj/afnetworking-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (4, 'Unix网络编程-笔记', 'https://www.gitbook.com/download/pdf/book/suzhenyu/unix', 'https://www.gitbook.com/book/suzhenyu/unix', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (5, 'ComputerNetWork', 'https://www.gitbook.com/download/pdf/book/rookiejx/computernetwork', 'https://www.gitbook.com/book/rookiejx/computernetwork', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (6, '神经网络与深度学习', 'https://www.gitbook.com/download/pdf/book/hit-scir/neural-networks-and-deep-learning-zh_cn', 'https://www.gitbook.com/book/hit-scir/neural-networks-and-deep-learning-zh_cn', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (7, 'ApacheSpark的设计与实现', 'https://www.gitbook.com/download/pdf/book/yourtion/sparkinternals', 'https://www.gitbook.com/book/yourtion/sparkinternals', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (8, 'HT-A9901(6U)数字IP网络工控主机-说明书', 'https://www.gitbook.com/download/pdf/book/fireboy38/ht-a9901-6u-ip-', 'https://www.gitbook.com/book/fireboy38/ht-a9901-6u-ip-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (9, '开始一段网络编辑文档的经历', 'https://www.gitbook.com/download/pdf/book/wishmo/beginmarker', 'https://www.gitbook.com/book/wishmo/beginmarker', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (10, 'SocialNetworkAnalysis', 'https://www.gitbook.com/download/pdf/book/jirlong/social-network-analysis', 'https://www.gitbook.com/book/jirlong/social-network-analysis', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (11, 'NginxConfigurationManual', 'https://www.gitbook.com/download/pdf/book/qqbook/nginx-configuration-manual', 'https://www.gitbook.com/book/qqbook/nginx-configuration-manual', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (12, 'ApacheShiro1.2.xReferenceManual中文翻译', 'https://www.gitbook.com/download/pdf/book/waylau/apache-shiro-1-2-x-reference', 'https://www.gitbook.com/book/waylau/apache-shiro-1-2-x-reference', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (13, 'ApacheCordovaDevelopmentGuide.《ApacheCordova开发指南》', 'https://www.gitbook.com/download/pdf/book/waylau/cordova-dev-guide', 'https://www.gitbook.com/book/waylau/cordova-dev-guide', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (14, 'Nginx学习笔记', 'https://www.gitbook.com/download/pdf/book/skyao/leaning-nginx', 'https://www.gitbook.com/book/skyao/leaning-nginx', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (15, 'Unity多人連線教學', 'https://www.gitbook.com/download/pdf/book/kagami3421/unitynetworking-zh_tw', 'https://www.gitbook.com/book/kagami3421/unitynetworking-zh_tw', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (16, 'go网络编程', 'https://www.gitbook.com/download/pdf/book/liufuqiang/network-programming-with-go', 'https://www.gitbook.com/book/liufuqiang/network-programming-with-go', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (17, 'Nginx', 'https://www.gitbook.com/download/pdf/book/helios_hook/nginx', 'https://www.gitbook.com/book/helios_hook/nginx', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (18, '关于使用ApacheHadoop平台框架的解决方案', 'https://www.gitbook.com/download/pdf/book/everhopingandwaiting/j_yao_suse', 'https://www.gitbook.com/book/everhopingandwaiting/j_yao_suse', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (19, '网络编码应用与实战', 'https://www.gitbook.com/download/pdf/book/kingstones/networkcodingapplicationandpractice', 'https://www.gitbook.com/book/kingstones/networkcodingapplicationandpractice', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (20, 'Nginx开发从入门到精通', 'https://www.gitbook.com/download/pdf/book/cooljacket/nginx_from_starter_to_master', 'https://www.gitbook.com/book/cooljacket/nginx_from_starter_to_master', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (21, 'apache_kafka_guid', 'https://www.gitbook.com/download/pdf/book/dtcui/apache_kafka_guid', 'https://www.gitbook.com/book/dtcui/apache_kafka_guid', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (22, 'Beej''sGuidetoNetworkProgramming正體中文版', 'https://www.gitbook.com/download/pdf/book/myliao/beej-s-guide-to-network-programming-chinese-zhtw', 'https://www.gitbook.com/book/myliao/beej-s-guide-to-network-programming-chinese-zhtw', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (23, 'Unity連線概觀', 'https://www.gitbook.com/download/pdf/book/kagami3421/unitynetworkoverview', 'https://www.gitbook.com/book/kagami3421/unitynetworkoverview', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (24, 'nginx-zh', 'https://www.gitbook.com/download/pdf/book/aceld/nginx-zh', 'https://www.gitbook.com/book/aceld/nginx-zh', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (25, 'Nginx中文官方文档', 'https://www.gitbook.com/download/pdf/book/wizardforcel/nginx-doc', 'https://www.gitbook.com/book/wizardforcel/nginx-doc', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (26, '网络记录', 'https://www.gitbook.com/download/pdf/book/record/web', 'https://www.gitbook.com/book/record/web', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (27, 'Boost.AsioC++网络编程', 'https://www.gitbook.com/download/pdf/book/mmoaay/boost-asio-cpp-network-programming-chinese', 'https://www.gitbook.com/book/mmoaay/boost-asio-cpp-network-programming-chinese', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (28, '神经网络和深度学习', 'https://www.gitbook.com/download/pdf/book/moonlet/neural-networks-and-deep-learning-sc', 'https://www.gitbook.com/book/moonlet/neural-networks-and-deep-learning-sc', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (29, '深入理解Neutron--OpenStack网络实现', 'https://www.gitbook.com/download/epub/book/yeasy/openstack_understand_neutron', 'https://www.gitbook.com/book/yeasy/openstack_understand_neutron', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (30, '神经网络与深度学习（翻译）', 'https://www.gitbook.com/download/pdf/book/andylei77/-neural-networks-and-deep-learning', 'https://www.gitbook.com/book/andylei77/-neural-networks-and-deep-learning', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (31, '卷积神经网络', 'https://www.gitbook.com/download/pdf/book/autocyz/-cnn', 'https://www.gitbook.com/book/autocyz/-cnn', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (32, 'ApacheMINAUserGuide中文翻译《ApacheMINA2用户指南》', 'https://www.gitbook.com/download/pdf/book/waylau/apache-mina-2-user-guide', 'https://www.gitbook.com/book/waylau/apache-mina-2-user-guide', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (33, '跨平台多线程服务端编程:使用asioC++网络库', 'https://www.gitbook.com/download/pdf/book/cppbook/asio', 'https://www.gitbook.com/book/cppbook/asio', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (34, 'ApacheKafkaDocumentationCN', 'https://www.gitbook.com/download/pdf/book/ddfeng/apache-kafka-documentation-cn', 'https://www.gitbook.com/book/ddfeng/apache-kafka-documentation-cn', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (35, '网络基本功系列', 'https://www.gitbook.com/download/pdf/book/wizardforcel/network-basic', 'https://www.gitbook.com/book/wizardforcel/network-basic', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (36, '密码学与网络安全协议工具箱', 'https://www.gitbook.com/download/pdf/book/tcz001/crypto-proto-toolkit', 'https://www.gitbook.com/book/tcz001/crypto-proto-toolkit', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (37, 'FarmingUrbanismNetwork', 'https://www.gitbook.com/download/pdf/book/cheweiliu/farming-urbanism-network', 'https://www.gitbook.com/book/cheweiliu/farming-urbanism-network', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (38, '神经网络', 'https://www.gitbook.com/download/pdf/book/jeffor/nerve_net', 'https://www.gitbook.com/book/jeffor/nerve_net', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (39, '太一网络研发', 'https://www.gitbook.com/download/pdf/book/qizisheng/t1', 'https://www.gitbook.com/book/qizisheng/t1', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (40, 'THENETWORKLIFEOFSISE', 'https://www.gitbook.com/download/pdf/book/bessie/the-network-life-of-sise', 'https://www.gitbook.com/book/bessie/the-network-life-of-sise', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (41, 'Nginx开发从入门到精通', 'https://www.gitbook.com/download/pdf/book/wuleying/nginx-book', 'https://www.gitbook.com/book/wuleying/nginx-book', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (42, '神经网络与深度学习', 'https://www.gitbook.com/download/pdf/book/tigerneil/neural-networks-and-deep-learning-zh', 'https://www.gitbook.com/book/tigerneil/neural-networks-and-deep-learning-zh', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (43, '深入理解Neutron--OpenStack网络实现', 'https://www.gitbook.com/download/pdf/book/yeasy/openstack_understand_neutron', 'https://www.gitbook.com/book/yeasy/openstack_understand_neutron', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (44, 'Tengine/Nginx源码分析', 'https://www.gitbook.com/download/pdf/book/jimingmin/tengine-', 'https://www.gitbook.com/book/jimingmin/tengine-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (45, 'Learn­Nginx', 'https://www.gitbook.com/download/pdf/book/domy/nginx', 'https://www.gitbook.com/book/domy/nginx', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (46, '关于nginx起不来的问题', 'https://www.gitbook.com/download/pdf/book/xiongming/nginxstatus', 'https://www.gitbook.com/book/xiongming/nginxstatus', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (47, '网络安全加固', 'https://www.gitbook.com/download/pdf/book/midui/-net1', 'https://www.gitbook.com/book/midui/-net1', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (48, '网络安全与攻击工具', 'https://www.gitbook.com/download/pdf/book/aceld/attack-tool', 'https://www.gitbook.com/book/aceld/attack-tool', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (49, 'ApacheFlume', 'https://www.gitbook.com/download/pdf/book/lv-neo/flume', 'https://www.gitbook.com/book/lv-neo/flume', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (50, '信息网络协议课程复习', 'https://www.gitbook.com/download/pdf/book/iamabug/islr', 'https://www.gitbook.com/book/iamabug/islr', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (51, 'neural-networks-and-deep-learning-notes-v0.8', 'https://www.gitbook.com/download/pdf/book/ljalphabeta/neural-networks-and-deep-learning-notes', 'https://www.gitbook.com/book/ljalphabeta/neural-networks-and-deep-learning-notes', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (52, 'ComputerNetwork', 'https://www.gitbook.com/download/pdf/book/tinyorkzheng/computernetwork', 'https://www.gitbook.com/book/tinyorkzheng/computernetwork', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (53, '神经网络与深度学习课后习题', 'https://www.gitbook.com/download/pdf/book/jyihuo/neural_network', 'https://www.gitbook.com/book/jyihuo/neural_network', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (54, '关于浏览器和网络的20项须知', 'https://www.gitbook.com/download/pdf/book/wizardforcel/20-things-i-learned', 'https://www.gitbook.com/book/wizardforcel/20-things-i-learned', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (55, 'Centos基于Apache的Tomcat负载均衡和集群', 'https://www.gitbook.com/download/pdf/book/szogroup/centos-apache-tomcat', 'https://www.gitbook.com/book/szogroup/centos-apache-tomcat', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (56, 'nginxloadingbalance', 'https://www.gitbook.com/download/pdf/book/emaeshuang/nginx', 'https://www.gitbook.com/book/emaeshuang/nginx', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (57, 'ApacheBeam中文文档', 'https://www.gitbook.com/download/pdf/book/bchen-talend/apache-beam-chinese-document', 'https://www.gitbook.com/book/bchen-talend/apache-beam-chinese-document', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (58, 'ApacheSpark学习笔记', 'https://www.gitbook.com/download/pdf/book/zhoujiagen/notes-of-spark', 'https://www.gitbook.com/book/zhoujiagen/notes-of-spark', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (59, 'apache-shiro', 'https://www.gitbook.com/download/pdf/book/jiaoqing/apache-shiro', 'https://www.gitbook.com/book/jiaoqing/apache-shiro', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (60, '关于闪电网络的翻译整理', 'https://www.gitbook.com/download/pdf/book/yichentang/-', 'https://www.gitbook.com/book/yichentang/-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (61, '我見我思Networkprogramming', 'https://www.gitbook.com/download/pdf/book/wirelessr/-network-programming', 'https://www.gitbook.com/book/wirelessr/-network-programming', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (62, 'Neural-Networks-and-Deep-Learning-笔记', 'https://www.gitbook.com/download/pdf/book/basicv8vc/neural-networks-and-deep-learning-notes', 'https://www.gitbook.com/book/basicv8vc/neural-networks-and-deep-learning-notes', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (63, '蜘蛛：社会网络分析技术', 'https://www.gitbook.com/download/pdf/book/etdeng/-', 'https://www.gitbook.com/book/etdeng/-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (64, 'NetworkPacketProgramming網路封包程式設計', 'https://www.gitbook.com/download/pdf/book/qbsuranalang/network-packet-programming', 'https://www.gitbook.com/book/qbsuranalang/network-packet-programming', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (65, 'ApacheJena偷吃步', 'https://www.gitbook.com/download/pdf/book/kazafchen/apache-jena', 'https://www.gitbook.com/book/kazafchen/apache-jena', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (66, 'Twisted网络编程60秒', 'https://www.gitbook.com/download/pdf/book/cygnushan/twisted-web-in-60-seconds', 'https://www.gitbook.com/book/cygnushan/twisted-web-in-60-seconds', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (67, '梦想加网络维护', 'https://www.gitbook.com/download/pdf/book/billdreamplus/mydreamplus-network', 'https://www.gitbook.com/book/billdreamplus/mydreamplus-network', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (68, 'ApacheHBase™参考指南', 'https://www.gitbook.com/download/pdf/book/korder/hbase-rg', 'https://www.gitbook.com/book/korder/hbase-rg', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (69, 'nginx1.8+php5.2.17+mysql5.5(lnmp)', 'https://www.gitbook.com/download/pdf/book/ownlearn/nginx1-8-php5-2-17-mysql5-5-lnmp-', 'https://www.gitbook.com/book/ownlearn/nginx1-8-php5-2-17-mysql5-5-lnmp-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (70, 'ApacheSpark源码阅读', 'https://www.gitbook.com/download/pdf/book/ihainan/spark-source-code', 'https://www.gitbook.com/book/ihainan/spark-source-code', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (71, 'iOS网络笔记', 'https://www.gitbook.com/download/pdf/book/hirodong/ios-', 'https://www.gitbook.com/book/hirodong/ios-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (72, 'ApacheSpark部署文档中文版', 'https://www.gitbook.com/download/pdf/book/qiongluo/apache-spark-deploying-zh_cn', 'https://www.gitbook.com/book/qiongluo/apache-spark-deploying-zh_cn', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (73, '网络多线程', 'https://www.gitbook.com/download/pdf/book/fangfangluo/-thread', 'https://www.gitbook.com/book/fangfangluo/-thread', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (74, '计算机网络基础自考重点', 'https://www.gitbook.com/download/pdf/book/happle/-', 'https://www.gitbook.com/book/happle/-', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (75, '网络安全', 'https://www.gitbook.com/download/pdf/book/germey/net-security', 'https://www.gitbook.com/book/germey/net-security', '09', '20161209123505');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (76, '数据挖掘与数据化运营实战：思路、方法、技巧与应用', 'https://www.gitbook.com/download/pdf/book/jobrest/datamining-om-by-data', 'https://www.gitbook.com/book/jobrest/datamining-om-by-data', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (77, 'GrowingIO分析百科', 'https://www.gitbook.com/download/pdf/book/wangliu123/growingiowiki', 'https://www.gitbook.com/book/wangliu123/growingiowiki', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (78, 'spark-ml-source-analysis', 'https://www.gitbook.com/download/pdf/book/endymecy/spark-ml-source-analysis', 'https://www.gitbook.com/book/endymecy/spark-ml-source-analysis', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (79, 'Spark1.6.1官方文档最新翻译中文版', 'https://www.gitbook.com/download/pdf/book/yunninglian/spark', 'https://www.gitbook.com/book/yunninglian/spark', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (80, 'Spark学习笔记', 'https://www.gitbook.com/download/pdf/book/dzhou/spark-learning-notes', 'https://www.gitbook.com/book/dzhou/spark-learning-notes', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (81, '語言標記與分析指南', 'https://www.gitbook.com/download/pdf/book/loperntu/daa', 'https://www.gitbook.com/book/loperntu/daa', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (82, '病原微生物高通量测序数据分析笔记', 'https://www.gitbook.com/download/pdf/book/indexofire/notebook_of_analyzing_pathogen_ngs_data', 'https://www.gitbook.com/book/indexofire/notebook_of_analyzing_pathogen_ngs_data', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (83, '語言分析與資料科學', 'https://www.gitbook.com/download/pdf/book/loperntu/ladsbook', 'https://www.gitbook.com/book/loperntu/ladsbook', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (84, '大数据资源共享', 'https://www.gitbook.com/download/pdf/book/opensourceteam/bigdata', 'https://www.gitbook.com/book/opensourceteam/bigdata', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (85, '机器学习个人笔记完整版v4.2', 'https://www.gitbook.com/download/pdf/book/wiilzhang/ml-v4-2', 'https://www.gitbook.com/book/wiilzhang/ml-v4-2', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (86, 'Cayman非结构化数据仓库', 'https://www.gitbook.com/download/pdf/book/tech-datatom/cayman-v', 'https://www.gitbook.com/book/tech-datatom/cayman-v', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (87, 'Spark编程实践', 'https://www.gitbook.com/download/pdf/book/l0he1g/spark-', 'https://www.gitbook.com/book/l0he1g/spark-', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (88, 'SparkStreaming学习笔记', 'https://www.gitbook.com/download/pdf/book/kevinhjk/sparkstreaming', 'https://www.gitbook.com/book/kevinhjk/sparkstreaming', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (89, 'undersercore源码分析', 'https://www.gitbook.com/download/pdf/book/yoyoyohamapi/undersercore-analysis', 'https://www.gitbook.com/book/yoyoyohamapi/undersercore-analysis', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (90, 'Swoole源码分析', 'https://www.gitbook.com/download/pdf/book/ipersi/swoole_code', 'https://www.gitbook.com/book/ipersi/swoole_code', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (91, 'Android通用开源项目分析及实现', 'https://www.gitbook.com/download/pdf/book/panthole/android-open-project-analysis-realize', 'https://www.gitbook.com/book/panthole/android-open-project-analysis-realize', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (92, '大数据处理常用技术有哪些', 'https://www.gitbook.com/download/pdf/book/candy_zhao/-', 'https://www.gitbook.com/book/candy_zhao/-', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (93, '面向程序员的数据挖掘指南', 'https://www.gitbook.com/download/pdf/book/yourtion/dataminingguide', 'https://www.gitbook.com/book/yourtion/dataminingguide', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (94, '應用程式分析工具', 'https://www.gitbook.com/download/pdf/book/stephanalber/facebook-analytics-for-apps-cn', 'https://www.gitbook.com/book/stephanalber/facebook-analytics-for-apps-cn', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (95, '数据挖掘实战', 'https://www.gitbook.com/download/pdf/book/czhouyi/data-mining', 'https://www.gitbook.com/book/czhouyi/data-mining', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (96, 'spark-graphx-source-analysis', 'https://www.gitbook.com/download/pdf/book/endymecy/spark-graphx-source-analysis', 'https://www.gitbook.com/book/endymecy/spark-graphx-source-analysis', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (97, '华美赛佳GDS数据库脚本说明手册', 'https://www.gitbook.com/download/pdf/book/shixiong77/gds_database_manual', 'https://www.gitbook.com/book/shixiong77/gds_database_manual', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (98, '告诉你外语学习的真实方法及误区分析', 'https://www.gitbook.com/download/pdf/book/english/howto', 'https://www.gitbook.com/book/english/howto', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (99, '敏捷思维：移动互联网和大数据时代IT企业转型、升级与再造之道', 'https://www.gitbook.com/download/pdf/book/jobrest/thinking-in-agile', 'https://www.gitbook.com/book/jobrest/thinking-in-agile', '08', '20161209123530');
INSERT INTO gitbook (SEQ, book_name, book_path, book_info, SORT_INFO, create_date) VALUES (100, 'Hyperledger源码分析之Fabric', 'https://www.gitbook.com/download/pdf/book/yeasy/hyperledger_code_fabric', 'https://www.gitbook.com/book/yeasy/hyperledger_code_fabric', '08', '20161209123530');
