server:
  port: 8999
  compression:
          min-response-size: 512
          enabled: true
          mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
spring:
  datasource:
          url: jdbc:mysql://127.0.0.1:3306/demo
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 1
          max-active: 20
          test-on-borrow: true
  freemarker:
    suffix: .ftl
    charset: UTF-8
    cache: false
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path: classpath:/templates/

#在Springboot中默认的静态资源路径有：classpath:/META-INF/resources/，classpath:/resources/，classpath:/static/，classpath:/public/，
#从这里可以看出这里的静态资源路径都是在classpath中
#在这个最末尾的file:${web.upload-path}之所有要加file:是因为指定的是一个具体的硬盘路径
  resources:
    static-locations: classpath:/resources/, classpath:/static/,classpath:/public/,file:${web.upload-path}
  mvc:
    static-path-pattern: /**

#spring.mvc.static-path-pattern=/**表示所有的访问都经过静态资源路径；
#  mvc:
#    static-path-pattern: /**
mybatis:
  typeAliasesPackage: com.dreamertn9527
  mapper-locations: classpath:mapper/**.xml
logging:
  file: /var/logs/dreamertn9527.log
  level: debug

#pagehelper.config：pagehelper-config.xml配置文件的路径
#pagehelper.typeHandlersPackage：扫描typeHandlers的包
#pagehelper.checkConfigLocation：检查配置文件是否存在
#pagehelper.executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
