server:
  port: 8081
  compression:
          min-response-size: 512
          enabled: true
          mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
spring:
  datasource:
          url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          initial-size: 10
          max-active: 50
          test-on-borrow: true
          min-idle: 5
          filters: stat,wall,log4j
          logSlowSql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 10000
      max-wait: 100
      max-idle: 10000
      min-idle: 500
    timeout: 10
  freemarker:
    suffix: .ftl
    charset: UTF-8
    cache: false
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path: classpath:/templates/

#在Springboot中默认的静态资源路径有：classpath:/META-INF/resources/，classpath:/resources/，classpath:/static/，classpath:/public/，
#从这里可以看出这里的静态资源路径都是在classpath中
#在这个最末尾的file:${web.upload-path}之所有要加file:是因为指定的是一个具体的硬盘路径
  resources:
    static-locations: classpath:/resources/, classpath:/static/,classpath:/public/,file:${web.upload-path}
  mvc:
    static-path-pattern: /**
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      database: dreamer
      host: 127.0.0.1
      port: 27017
#
##spring.mvc.static-path-pattern=/**表示所有的访问都经过静态资源路径；
##  mvc:
##    static-path-pattern: /**
#mybatis:
#  typeAliasesPackage: com.dreamertn9527.dreamertn9527.domain
#  mapper-locations: classpath:mapper/**.xml
logging:
  level:
    root: error
    org.springframework.web: error
